name: healthfix
description: Mobile E-commerce Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.0
  enum_to_string: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.3
  flutter_tags: ^0.4.9+1
  future_progress_dialog: ^0.2.0
  image_picker: ^0.8.4+6
  intl: ^0.17.0
  logger: ^1.1.0
  permission_handler: ^8.3.0
  # pinch_zoom_image_updated: ^0.2.6
  provider: ^6.0.2
  string_validator: ^0.3.0
  swipedetector: ^1.2.0
  url_launcher: ^6.0.18
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.6
  carousel_slider: ^4.0.0
  google_fonts: 2.2.0
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.1-nullsafety.0
  flutter_slider_indicator: ^1.0.0
  flex_color_picker: ^2.2.0
  pretty_json: ^2.0.0
  flutter_toggle_tab: ^1.1.7
  flutter_local_notifications: ^9.2.0
  firebase_messaging: ^11.2.6
  new_version: ^0.3.0
  timelines: ^0.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/hf-logo-only.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/menu/
    - assets/images/trainers/
    - assets/icons/
    - assets/icons/app/
    - assets/logo/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300